### ISSUE TITLE
imap: command not found

### ISSUE THREAD

**Issue by yudouZ** [wheelheart/apollo_map#3]

**Comment by yudouZ** [comment]
I'm stuck on this problem, could you tell me how to solve it?
![22E5438437D1741B58BEB9F766CD950B](https://github.com/user-attachments/assets/ae234ddd-dfcb-436a-b7d4-36f58014a87f)

**Comment by yudouZ** [comment]
I also run it outside the docker container.

**Comment by daohu527** [comment]
The reason is you didn't install `imap`

Install imap first
```
pip3 install imap_box
```

**Comment by yudouZ** [comment]
Thanks, the problem is solved
